### ISSUE TITLE
Change of IncSearch color

### ISSUE THREAD

**Issue by flexo3001** [ajgrf/sprinkles#1]
Ohai,
would it be possible to change the background-color from yellow to something else (i used cyan in my tests)? In some terminals you loose the cursor on IncSearch and in case you are using a substitution (e.g. %s/foo/bar) you need to count the substitutions instead of seeing on which change you are.

Best,
Marco

**Comment by ajgrf** [comment]
I'm open to making a change here, but I don't understand the rationale. Which terminals have this issue and why isn't there a problem when the background is cyan instead of yellow?

**Comment by flexo3001** [comment]
I'm using termite and not sure if it's term dependent. The difference between yellow and any other color is that you can see the current postion of the substitution (which is denoted by the other color like cyan). On the normal search the term-cursor moves forward/backward when going to the next/prev match. On substitution there's no term-cursor so you have to count to get the current position (no color difference when both are yellow).

**Comment by ajgrf** [comment]
Okay, so if I understand correctly, the issue is that Search and IncSearch are both yellow. If I changed both of them to cyan there would still be an issue, right?

**Comment by flexo3001** [comment]
Yes. In the picture you can see the difference. In the left you can see the changed IncSearch and on the right with default (on both i did :%s/set/foo/gc for substitution with the option to choose).
![2015-10-22-011608_1366x768_scrot](https://cloud.githubusercontent.com/assets/1415596/10652899/82fa8e62-785a-11e5-814d-5fdbd5ee5c47.png)

**Comment by ajgrf** [comment]
Okay, learning about the c flag in substitutions made the issue a lot clearer. I just pushed a fix. I'm not 100% happy with the style, but if I change the color again in the future I'll make sure Search and IncSearch are still distinct.

**Comment by flexo3001** [comment]
Oh i just saw that i forgot the c flag in the first place. No wonder it wasn't clear. 
Thank you for the nice colorscheme.
Best Marco
